name: Purge Branches

on:
  # Allow manual triggering of the workflow
  workflow_dispatch:
  
  # Scheduled execution - Every day at 10 AM IST (3:30 AM UTC)
  schedule:
    - cron: '00 03 * * *'

jobs:
  purgeBranches:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to delete branches

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Purge and Notify Branches
        uses: gita-vahdatinia/purge-branch@v1
        with:
          token: ${{ secrets.MY_TOKEN }}   # Your GitHub personal access token
          days-to-notify: 1               # Notify branches 1 day before deletion
          days-to-delete: 5               # Delete branches older than 5 days
